hexapod_locomotion_node:
  ros__parameters:
    use_sim_time: True

    # Robot geometry (mm / rad)
    L1: 60.55
    L2: 73.84
    L3: 112.16
    body_radius: 100.0
    beta_angle: 1.0977

    # Home foot position
    home_x: 170.0  
    home_y: 0.0
    home_z: -95.0   

    # Gait parameters
    step_length: 50.0
    step_height: 15.0
    step_period: 16.0

    standby_coxa:  0.0
    standby_femur: 0.3086
    standby_tibia: -1.3244

    standby_duration: 5.0

    update_rate: 50.0

    leg_controllers:
      - leg_0_controller
      - leg_1_controller
      - leg_2_controller
      - leg_3_controller
      - leg_4_controller
      - leg_5_controller