/**:
  ros__parameters:

    conn:
      heartbeat_rate: 1.0       
      heartbeat_mav_type: 2    
      timeout: 60.0            
      timesync_rate: 10.0

    sys:
      conn_timeout: 120.0    
      disable_diag: true      

    param:
      startup_timeout: 120.0
      pull_timeout: 120.0
      retries: 20

    distance_sensor:
      rangefinder_pub:
        id: 0
        frame_id: "tf_mini_link"
        field_of_view: 0.0523    
        sensor_position:
          x: 0.0
          y: 0.0
          z: -0.05
